name: Cypress Tests

on: [deployment_status]

jobs:
  cypress-percy:
    # Sender id is Vercel's
    if: github.event.deployment_status.state == 'success' && github.event.sender.id == 35613825
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    steps:
      - name: Checkout ðŸ›Ž
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Setup Node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: '16'
        # Get the branch name from the commit SHA
      - name: Set branch name
        run: echo "BRANCH=$(git name-rev --name-only $GITHUB_SHA | awk -F / '{print $3}')" >> $GITHUB_ENV
      - name: Run Cypress ðŸŒ²
        uses: cypress-io/github-action@v2 # TSCCR: tsccr: could not find entry for cypress-io/github-action
        with:
          browser: chrome
          headless: true
          record: true
          parallel: true
          group: 'GitHub Actions'
          command-prefix: '@percy/cli exec -t 500 -- npx'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Pass the Vercel reported environment (Preview or Production) through to Cypress
          # This is used for conditional tests: enterpriseTrials.spec.js and salesFormPage.spec.js
          CYPRESS_DEPLOY_ENVIRONMENT: ${{ github.event.deployment.environment }}
          # We pass the gh token to allow Cypress to detect re-runs accurately.
          # See https://github.com/cypress-io/github-action
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          PERCY_TARGET_BRANCH: 'master'
          # Use the branch name set in the 'Set branch name' job above
          PERCY_BRANCH: ${{ env.BRANCH }}
          COMMIT_INFO_BRANCH: ${{ env.BRANCH }}
          # Should match the total in matrix:containers
          PERCY_PARALLEL_TOTAL: 3
          PERCY_PARALLEL_NONCE: '${{ github.event_name }}-${{ github.sha }}'
